CREATE TABLE tweet(
	id SERIAL PRIMARY KEY,
	body TEXT,
	added_time TIMESTAMP
);

CREATE TABLE users(
	id SERIAL PRIMARY KEY,
	unique_id VARCHAR(52) UNIQUE NOT NULL,
	username VARCHAR(52),
	password VARCHAR(256)
);